theme: jekyll-theme-minimal

title: Bin Yu Personal Page
show_downloads: false
logo: Image.jpg
author: Bin YU 于滨
social-network-links:
  email: "biny@umass.edu"
description: Umass Amherst ECE Master Student
description: Welcome to Bin Yu personal site. Here is my <a href="Resume_Bin-Yu_PDF.pdf">CV (2021)</a>
