theme: jekyll-theme-minimal

title: Bin Yu Personal Page
show_downloads: false
logo: Image.jpg
description: Welcome to Bin Yu personal site. Here is my <a href="Resume_Bin-Yu_PDF.pdf">CV (2021)</a>.
Bin Yu 于滨\
Master Candidate\
Department of Eletrical and Computer Engineering\
University of Massachusetts Amherst\
Email: biny at umass dot edu\
